name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Update submodule
      run: |
        cd binaryninjaapi
        git fetch --tags
        git checkout --force ${{matrix.version.name}}
        git submodule update --init --recursive
    - name: Patch api to allow building headlessly
      if: ${{ matrix.version.use-patch }}
      shell: bash
      run: |
        cd binaryninjaapi
        git apply --verbose ${{matrix.version.patch-file}} 
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.name}}-${{matrix.version.name}}
        path: ${{github.workspace}}/build/*TestPlugin*
